export const propertyAddValues = {
  name: '',
  constructorName: '',
  companyName: '',
  totalNumber: '',
  dateRange: {
    startDate: '',
    endDate: '',
  },
  areas: [],
  files: [],
  areaAddr: '',
  modelhouseAddr: '',
  keywords: [],
  addrDo: '',
  addrGu: '',
  addrDong: '',
  buildingName: '',
  phoneNumber: '',
  homepage: '',
  contactChannel: '',
};
