export const propertyAddValues = {
  propertyName: '',
  propertyConstructor: '',
  propertyCompanyName: '',
  propertyTotalNumber: '',
  dateRange: {
    startDate: '',
    endDate: '',
  },
  areas: [],
  files: [],
  propertyAreaAddr: '',
  propertyModelhouseAddr: '',
  keywords: [],
  addrDo: '',
  addrGu: '',
  addrDong: '',
  buildingName: '',
  phoneNumber: '',
  homepage: '',
  contactChannel: '',
};
