export type propertyAddTypes =
  | 'propertyName'
  | 'propertyConstructor'
  | 'propertyCompanyName'
  | 'propertyTotalNumber'
  | 'files'
  | 'areas'
  | 'propertyAreaAddr'
  | 'propertyModelhouseAddr'
  | 'addrDo'
  | 'addrGu'
  | 'addrDong'
  | 'buildingName'
  | 'phoneNumber'
  | 'homepage'
  | 'contactChannel'
  | 'dateRange'
  | 'keywords';
