export type propertyAddTypes =
  | 'name'
  | 'constructorName'
  | 'companyName'
  | 'totalNumber'
  | 'files'
  | 'areas'
  | 'areaAddr'
  | 'modelhouseAddr'
  | 'addrDo'
  | 'addrGu'
  | 'addrDong'
  | 'buildingName'
  | 'phoneNumber'
  | 'homepage'
  | 'contactChannel'
  | 'dateRange'
  | 'keywords';
